//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace WordVSTO_TemplateProject {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl1;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl dt_date;
        
        internal Microsoft.Office.Tools.Word.ComboBoxContentControl comboBoxContentControl1;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl2;
        
        internal Microsoft.Office.Tools.Word.ComboBoxContentControl comboBoxContentControl2;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl3;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl5;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl6;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl txt_empName;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl txt_empID;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl txt_manager;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl txt_jobTitle;
        
        internal Microsoft.Office.Tools.Word.DropDownListContentControl dd_department;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl rtst_infraction;
        
        internal Microsoft.Office.Tools.Word.GroupContentControl groupContentControl1;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.richTextContentControl1.BeginInit();
            this.dt_date.BeginInit();
            this.comboBoxContentControl1.BeginInit();
            this.richTextContentControl2.BeginInit();
            this.comboBoxContentControl2.BeginInit();
            this.richTextContentControl3.BeginInit();
            this.richTextContentControl5.BeginInit();
            this.richTextContentControl6.BeginInit();
            this.txt_empName.BeginInit();
            this.txt_empID.BeginInit();
            this.txt_manager.BeginInit();
            this.txt_jobTitle.BeginInit();
            this.dd_department.BeginInit();
            this.rtst_infraction.BeginInit();
            this.groupContentControl1.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.groupContentControl1.EndInit();
            this.rtst_infraction.EndInit();
            this.dd_department.EndInit();
            this.txt_jobTitle.EndInit();
            this.txt_manager.EndInit();
            this.txt_empID.EndInit();
            this.txt_empName.EndInit();
            this.richTextContentControl6.EndInit();
            this.richTextContentControl5.EndInit();
            this.richTextContentControl3.EndInit();
            this.comboBoxContentControl2.EndInit();
            this.richTextContentControl2.EndInit();
            this.comboBoxContentControl1.EndInit();
            this.dt_date.EndInit();
            this.richTextContentControl1.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.richTextContentControl1 = Globals.Factory.CreateRichTextContentControl(null, null, "254023022", "richTextContentControl1", this);
            this.dt_date = Globals.Factory.CreateDatePickerContentControl(null, null, "2574760878", "dt_date", this);
            this.comboBoxContentControl1 = Globals.Factory.CreateComboBoxContentControl(null, null, "3804868083", "comboBoxContentControl1", this);
            this.richTextContentControl2 = Globals.Factory.CreateRichTextContentControl(null, null, "31626113", "richTextContentControl2", this);
            this.comboBoxContentControl2 = Globals.Factory.CreateComboBoxContentControl(null, null, "2143143313", "comboBoxContentControl2", this);
            this.richTextContentControl3 = Globals.Factory.CreateRichTextContentControl(null, null, "1499772576", "richTextContentControl3", this);
            this.richTextContentControl5 = Globals.Factory.CreateRichTextContentControl(null, null, "3146531142", "richTextContentControl5", this);
            this.richTextContentControl6 = Globals.Factory.CreateRichTextContentControl(null, null, "354235688", "richTextContentControl6", this);
            this.txt_empName = Globals.Factory.CreatePlainTextContentControl(null, null, "1451362584", "txt_empName", this);
            this.txt_empID = Globals.Factory.CreatePlainTextContentControl(null, null, "4039827958", "txt_empID", this);
            this.txt_manager = Globals.Factory.CreatePlainTextContentControl(null, null, "4239489166", "txt_manager", this);
            this.txt_jobTitle = Globals.Factory.CreatePlainTextContentControl(null, null, "1050428595", "txt_jobTitle", this);
            this.dd_department = Globals.Factory.CreateDropDownListContentControl(null, null, "3753831536", "dd_department", this);
            this.rtst_infraction = Globals.Factory.CreateRichTextContentControl(null, null, "2875715981", "rtst_infraction", this);
            this.groupContentControl1 = Globals.Factory.CreateGroupContentControl(null, null, "3070064299", "groupContentControl1", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // richTextContentControl1
            // 
            this.richTextContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // dt_date
            // 
            this.dt_date.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // comboBoxContentControl1
            // 
            this.comboBoxContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl2
            // 
            this.richTextContentControl2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // comboBoxContentControl2
            // 
            this.comboBoxContentControl2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl3
            // 
            this.richTextContentControl3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl5
            // 
            this.richTextContentControl5.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl6
            // 
            this.richTextContentControl6.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txt_empName
            // 
            this.txt_empName.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txt_empID
            // 
            this.txt_empID.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txt_manager
            // 
            this.txt_manager.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txt_jobTitle
            // 
            this.txt_jobTitle.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // dd_department
            // 
            this.dd_department.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // rtst_infraction
            // 
            this.rtst_infraction.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // groupContentControl1
            // 
            this.groupContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // ThisDocument
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.groupContentControl1.Dispose();
            this.rtst_infraction.Dispose();
            this.dd_department.Dispose();
            this.txt_jobTitle.Dispose();
            this.txt_manager.Dispose();
            this.txt_empID.Dispose();
            this.txt_empName.Dispose();
            this.richTextContentControl6.Dispose();
            this.richTextContentControl5.Dispose();
            this.richTextContentControl3.Dispose();
            this.comboBoxContentControl2.Dispose();
            this.richTextContentControl2.Dispose();
            this.comboBoxContentControl1.Dispose();
            this.dt_date.Dispose();
            this.richTextContentControl1.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
